name: ${PROJECT_NAME:-sigeca_central}

services:
  db:
    container_name: ${PROJECT_NAME:-sigeca_central}_db
    image: postgres:latest
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
      - db_logs:/var/log/postgresql
      - ./sql/init:/docker-entrypoint-initdb.d
      - ./share:/share
  nifi:
    container_name: ${PROJECT_NAME:-sigeca_central}_nifi
    image: apache/nifi:${NIFI_VERSION:-2.0.0-M2}
    user: "0:0"
    environment:
      - NIFI_WEB_HTTPS_HOST=0.0.0.0
      - NIFI_WEB_HTTPS_PORT=${NIFI_WEB_HTTPS_PORT:-8443}
      - NIFI_WEB_PROXY_HOST=${DOMAIN_NAME}
      - SINGLE_USER_CREDENTIALS_USERNAME=${NIFI_USER}
      - SINGLE_USER_CREDENTIALS_PASSWORD=${NIFI_PASSWORD}
      - MAPA_SANITARIO_FQDN=${MAPA_SANITARIO_FQDN}
      - MAPA_SANITARIO_USERNAME=${MAPA_SANITARIO_USERNAME}
      - MAPA_SANITARIO_PASSWORD=${MAPA_SANITARIO_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - NIFI_PYTHON_PATH=/opt/nifi/nifi-current/python-scripts/
    # For debugging only
    # ports:
    #  - 8443:8443
    #  - 8081:8081
    volumes:
      - nifi_conf:/opt/nifi/nifi-current/conf
      - ./config/nifi/lib/postgresql-42.7.3.jar:/opt/nifi/nifi-current/lib/postgresql-42.7.3.jar
      - ./config/nifi/python-scripts/:/opt/nifi/nifi-current/python-scripts/
      - ./share:/share
  api:
    container_name: ${PROJECT_NAME:-sigeca_scentral}_api
    image: sigeca-api
    build: ./sigeca-api
    environment:
      - API_AUTH_SECRET_KEY=${API_AUTH_SECRET_KEY}
      - DB_HOST=db
      - DB_PORT=5432 # Port inside db container
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
  nginx:
    container_name: ${PROJECT_NAME:-sigeca_scentral}_nginx
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
      - ${DB_PORT:-5432}:5432
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/http.conf:/etc/nginx/conf.d/http.conf
      - ./config/nginx/postgres.conf:/etc/nginx/postgres.conf
      - ./config/nginx/ssl:/etc/nginx/ssl
      - ./share:/share

volumes:
  db_data:
    name: ${PROJECT_NAME:-sigeca_central}_db_data
  db_logs:
    name: ${PROJECT_NAME:-sigeca_central}_db_logs
  nifi_conf:
    name: ${PROJECT_NAME:-sigeca_central}_nifi_conf
  
networks:
  default:
    name: ${PROJECT_NAME:-sigeca_central}_network
